# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewTeam.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_viewTeam(object):
    def setupUi(self, viewTeam):
        viewTeam.setObjectName("viewTeam")
        viewTeam.resize(1162, 577)
        viewTeam.setAutoFillBackground(False)
        viewTeam.setStyleSheet("background-color: rgb(11, 12, 16); color: rgb(102, 252, 241);")
        self.teamNameLabel = QtWidgets.QLabel(viewTeam)
        self.teamNameLabel.setGeometry(QtCore.QRect(10, 10, 761, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.teamNameLabel.setFont(font)
        self.teamNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.teamNameLabel.setAutoFillBackground(False)
        self.teamNameLabel.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.teamNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.teamNameLabel.setObjectName("teamNameLabel")
        self.layoutWidget = QtWidgets.QWidget(viewTeam)
        self.layoutWidget.setGeometry(QtCore.QRect(780, 10, 371, 558))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.teamUpdateForm = QtWidgets.QFormLayout()
        self.teamUpdateForm.setObjectName("teamUpdateForm")
        self.captainLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.captainLabel.setFont(font)
        self.captainLabel.setObjectName("captainLabel")
        self.teamUpdateForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.captainLabel)
        self.captainComboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.captainComboBox.setFont(font)
        self.captainComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.captainComboBox.setObjectName("captainComboBox")
        self.teamUpdateForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.captainComboBox)
        self.wkLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wkLabel.setFont(font)
        self.wkLabel.setObjectName("wkLabel")
        self.teamUpdateForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.wkLabel)
        self.wkComboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wkComboBox.setFont(font)
        self.wkComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.wkComboBox.setObjectName("wkComboBox")
        self.teamUpdateForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wkComboBox)
        self.teamNameLabelForm = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.teamNameLabelForm.setFont(font)
        self.teamNameLabelForm.setObjectName("teamNameLabelForm")
        self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamNameLabelForm)
        self.teamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.teamNameLineEdit.setFont(font)
        self.teamNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.teamNameLineEdit.setObjectName("teamNameLineEdit")
        self.teamUpdateForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamNameLineEdit)
        self.dispTeamNameLabelForm = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dispTeamNameLabelForm.setFont(font)
        self.dispTeamNameLabelForm.setObjectName("dispTeamNameLabelForm")
        self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dispTeamNameLabelForm)
        self.displayTeamNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.displayTeamNameLineEdit.setFont(font)
        self.displayTeamNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.displayTeamNameLineEdit.setObjectName("displayTeamNameLineEdit")
        self.teamUpdateForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.displayTeamNameLineEdit)
        self.verticalLayout.addLayout(self.teamUpdateForm)
        self.updateTeamButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.updateTeamButton.setFont(font)
        self.updateTeamButton.setStyleSheet("color: rgb(31, 40, 51);\n"
"background-color: rgb(17, 100, 102);")
        self.updateTeamButton.setObjectName("updateTeamButton")
        self.verticalLayout.addWidget(self.updateTeamButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setStyleSheet("background-color: rgb(102, 252, 241);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setStyleSheet("background-color: rgb(102, 252, 241);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(218, 247, 166);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: rgb(218, 247, 166);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.addPlayerLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPlayerLabel.sizePolicy().hasHeightForWidth())
        self.addPlayerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.addPlayerLabel.setFont(font)
        self.addPlayerLabel.setAutoFillBackground(False)
        self.addPlayerLabel.setStyleSheet("background-color: rgb(44, 53, 49);")
        self.addPlayerLabel.setScaledContents(False)
        self.addPlayerLabel.setObjectName("addPlayerLabel")
        self.verticalLayout_2.addWidget(self.addPlayerLabel)
        self.addPlayerForm = QtWidgets.QFormLayout()
        self.addPlayerForm.setObjectName("addPlayerForm")
        self.fNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.fNameLabel.setObjectName("fNameLabel")
        self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fNameLabel)
        self.fNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fNameLineEdit.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.fNameLineEdit.setObjectName("fNameLineEdit")
        self.addPlayerForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fNameLineEdit)
        self.dobLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dobLabel.setObjectName("dobLabel")
        self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setStyleSheet("background-color: rgb(31, 40, 51); color: rgb(186, 189, 182);")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2001, 1, 1))
        self.dateEdit.setMinimumDate(QtCore.QDate(1950, 1, 1))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.addPlayerForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.battingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.battingStyleLabel.setObjectName("battingStyleLabel")
        self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.battingStyleLabel)
        self.battingStyleComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.battingStyleComboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.battingStyleComboBox.setObjectName("battingStyleComboBox")
        self.battingStyleComboBox.addItem("")
        self.battingStyleComboBox.addItem("")
        self.addPlayerForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.battingStyleComboBox)
        self.bowlingStyleLabel = QtWidgets.QLabel(self.layoutWidget)
        self.bowlingStyleLabel.setObjectName("bowlingStyleLabel")
        self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bowlingStyleLabel)
        self.bowlingStylecomboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bowlingStylecomboBox.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.bowlingStylecomboBox.setObjectName("bowlingStylecomboBox")
        self.bowlingStylecomboBox.addItem("")
        self.bowlingStylecomboBox.addItem("")
        self.addPlayerForm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bowlingStylecomboBox)
        self.verticalLayout_2.addLayout(self.addPlayerForm)
        self.addPlayerButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.addPlayerButton.setFont(font)
        self.addPlayerButton.setStyleSheet("background-color: rgb(17, 100, 102); color: rgb(31, 40, 51);")
        self.addPlayerButton.setObjectName("addPlayerButton")
        self.verticalLayout_2.addWidget(self.addPlayerButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(4, 3)
        self.verticalLayout_3.setStretch(5, 4)
        self.layoutWidget1 = QtWidgets.QWidget(viewTeam)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 80, 751, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.layoutWidget1)
        self.widget.setStyleSheet("background-color: rgb(31, 40, 51);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playerNameLabel = QtWidgets.QLabel(self.widget)
        self.playerNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerNameLabel.setObjectName("playerNameLabel")
        self.horizontalLayout.addWidget(self.playerNameLabel)
        self.verticalLayout_4.addWidget(self.widget)
        self.playerTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.playerTableWidget.setStyleSheet("background-color: rgb(44, 53, 49);")
        self.playerTableWidget.setObjectName("playerTableWidget")
        self.playerTableWidget.setColumnCount(0)
        self.playerTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.playerTableWidget)
        self.line_3 = QtWidgets.QFrame(viewTeam)
        self.line_3.setGeometry(QtCore.QRect(770, 10, 20, 551))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")

        self.retranslateUi(viewTeam)
        QtCore.QMetaObject.connectSlotsByName(viewTeam)

    def retranslateUi(self, viewTeam):
        _translate = QtCore.QCoreApplication.translate
        viewTeam.setWindowTitle(_translate("viewTeam", "Form"))
        self.teamNameLabel.setText(_translate("viewTeam", "Team Name"))
        self.captainLabel.setText(_translate("viewTeam", "Captain"))
        self.wkLabel.setText(_translate("viewTeam", "Wicket-Keeper"))
        self.teamNameLabelForm.setText(_translate("viewTeam", "Team Name"))
        self.dispTeamNameLabelForm.setText(_translate("viewTeam", "Display Name"))
        self.updateTeamButton.setText(_translate("viewTeam", "Update"))
        self.label.setText(_translate("viewTeam", "Current Captain :"))
        self.label_2.setText(_translate("viewTeam", "MS Dhoni"))
        self.label_3.setText(_translate("viewTeam", "Current WK :"))
        self.label_4.setText(_translate("viewTeam", "MS Dhoni"))
        self.addPlayerLabel.setText(_translate("viewTeam", " Add Player:"))
        self.fNameLabel.setText(_translate("viewTeam", "Full Name"))
        self.dobLabel.setText(_translate("viewTeam", "DOB"))
        self.dateEdit.setDisplayFormat(_translate("viewTeam", "dd/MM/yyyy"))
        self.battingStyleLabel.setText(_translate("viewTeam", "Batting Style"))
        self.battingStyleComboBox.setItemText(0, _translate("viewTeam", "Right Hand Bat"))
        self.battingStyleComboBox.setItemText(1, _translate("viewTeam", "Left Hand Bat"))
        self.bowlingStyleLabel.setText(_translate("viewTeam", "Bowling Style"))
        self.bowlingStylecomboBox.setItemText(0, _translate("viewTeam", "Right Hand Bowl"))
        self.bowlingStylecomboBox.setItemText(1, _translate("viewTeam", "Left Hand Bowl"))
        self.addPlayerButton.setText(_translate("viewTeam", "Add Player"))
        self.playerNameLabel.setText(_translate("viewTeam", "Player Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewTeam = QtWidgets.QWidget()
    ui = Ui_viewTeam()
    ui.setupUi(viewTeam)
    viewTeam.show()
    sys.exit(app.exec_())

